map_type: costmap

obstacle_range: 9.0
raytrace_range: 10.0

transform_tolerance: 1.0

#footprint: [[0.3, 0.3], [-0.3, 0.3], [-0.3, -0.3], [0.3, -0.3]]
robot_radius: 0.35
cost_scaling_factor: 10.0
min_in_place_vel_theta: 0.1  
min_vel_theta: -0.4  
max_vel_theta: 0.4  

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}

