local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   transform_tolerance: 1.0
   update_frequency: 10.0
   publish_frequency: 10.0
   width: 3.0
   height: 3.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   inflation_radius: 0.7
